// ============================================================================
//  minigameStyles.js — StyleSheet กลางของเครื่องเกม MiniGames (ธีมกระดาษครีม)
//  แยกออกจาก MiniGames.js เพื่อให้ไฟล์ logic สั้นลง และดู/แก้สไตล์ได้เป็นสัดส่วน
//  ใช้งาน:  import { S } from './minigameStyles';
// ============================================================================
import { StyleSheet } from 'react-native';

// ขอบซ้ายของการ์ดในไทม์ไลน์ sequence (รางอยู่ซ้ายของเส้นนี้) — ใช้ทั้งใน S.slotRow และ logic ของ SequenceGame
export const SEQ_PADL = 62;

export const S = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F7F1E5' },
  topBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#F7F1E5', paddingHorizontal: 16, paddingVertical: 10, borderBottomWidth: 2, borderBottomColor: '#2C1810' },
  backBtn: { paddingVertical: 4, paddingHorizontal: 2 },
  backTxt: { color: '#3A1A00', fontSize: 22, fontWeight: '900', fontFamily: 'Jersey', letterSpacing: 1 },
  title: { flex: 1, textAlign: 'center', fontSize: 19, color: '#C47A30', letterSpacing: 0.4, fontFamily: 'Jersey', fontWeight: '900' },
  bossTag: { width: 56, alignItems: 'flex-end' },
  bossTagTxt: { color: '#D94040', fontWeight: '900', fontSize: 14, letterSpacing: 1, fontFamily: 'Jersey' },
  parchment: { backgroundColor: '#EFE7DA', marginHorizontal: 14, marginTop: 12, borderRadius: 16, borderWidth: 2, borderColor: '#2C1810', paddingVertical: 11, paddingHorizontal: 14, borderBottomLeftRadius: 5 },
  parchmentBoss: { borderColor: '#D94040' },
  parLabel: { fontSize: 14, fontWeight: '900', color: '#C77A20', letterSpacing: 0.5, marginBottom: 3, fontFamily: 'Jersey' },
  parTxt: { fontSize: 15, color: '#4A2800', lineHeight: 23, fontFamily: 'PKNonthaburi' },
  hint: { color: '#6E441B', fontSize: 13, textAlign: 'center', marginVertical: 10, paddingHorizontal: 14, lineHeight: 19, fontFamily: 'PKNonthaburi' },
  section: { color: '#6E441B', fontSize: 14, fontWeight: '900', marginHorizontal: 14, marginTop: 14, marginBottom: 6, fontFamily: 'Jersey' },

  // wire — ถาดเครื่องมือ + แผงต่อวงจร
  wireCanvas: { width: '100%', marginTop: 8 },
  wireHit: { position: 'absolute', width: 48, height: 48, borderRadius: 24 },
  tray: { flexDirection: 'row', gap: 8, marginHorizontal: 14, marginTop: 12, padding: 8, backgroundColor: '#E6D8BE', borderRadius: 12, borderWidth: 2, borderColor: '#2C1810' },
  slot: { flex: 1, alignItems: 'center', gap: 4, paddingVertical: 8, borderRadius: 8, backgroundColor: '#F6F0E2', borderWidth: 1.5, borderColor: '#A9885E' },
  slotSel: { backgroundColor: '#F6E8CB', borderColor: '#C47A2D', shadowColor: '#000', shadowOpacity: 0.18, shadowRadius: 4, shadowOffset: { width: 0, height: 1 } },
  slotTxt: { color: '#6E441B', fontSize: 11.5, fontWeight: '800' },
  slotDot: { width: 6, height: 6, borderRadius: 3, marginTop: 1 },
  wireLabel: { position: 'absolute', color: '#4A2800', fontSize: 11.5, fontWeight: '700', lineHeight: 13 },
  wireTxt: { color: '#4A2800', fontSize: 16, fontWeight: '700', lineHeight: 20, fontFamily: 'PKNonthaburi' },
  wireIcon: { fontSize: 18 },
  wireArt: { width: 34, height: 34, borderRadius: 7, backgroundColor: '#FBF3DC', borderWidth: 1.3, borderColor: '#C9A24A', alignItems: 'center', justifyContent: 'center' },
  wireSym: { width: 34, height: 34, borderRadius: 7, backgroundColor: '#FBF3DC', borderWidth: 1.3, borderColor: '#C9A24A', alignItems: 'center', justifyContent: 'center' },
  wireTip: { color: '#6E441B', fontSize: 16, textAlign: 'center', marginTop: 14, marginHorizontal: 16, paddingVertical: 9, paddingHorizontal: 12, lineHeight: 22, backgroundColor: '#FBF3DC', borderRadius: 7, borderWidth: 1.5, borderColor: '#C9A24A', borderLeftWidth: 4, borderLeftColor: '#C47A2D', overflow: 'hidden', fontFamily: 'PKNonthaburi' },

  // wire / shared chips (legacy)
  wireRow: { flexDirection: 'row', gap: 12, paddingHorizontal: 14, paddingTop: 12 },
  col: { flex: 1, gap: 8 },
  chip: { backgroundColor: '#EFE7DA', borderRadius: 10, borderWidth: 2, borderColor: '#2C1810', padding: 10, alignItems: 'center', gap: 2 },
  chipActive: { borderColor: '#C47A2D', backgroundColor: '#F6E8CB' },
  chipTarget: { borderColor: '#C47A2D' },
  chipDone: { borderColor: '#2E7D32' },
  chipBad: { borderColor: '#D94040', backgroundColor: '#F6E3E0' },
  chipIcon: { fontSize: 20 },
  chipTxt: { color: '#4A2800', fontSize: 12.5, fontWeight: '700', textAlign: 'center', fontFamily: 'PKNonthaburi' },
  chipLink: { color: '#2E7D32', fontSize: 10.5, marginTop: 2 },

  // sort — โต๊ะแกะชิ้นส่วน + กล่อง
  benchHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, marginTop: 12 },
  benchTitle: { color: '#C47A30', fontSize: 14, fontWeight: '900', fontFamily: 'Jersey' },
  benchCount: { color: '#9A8569', fontSize: 12, fontWeight: '700' },
  bench: {
    flexDirection: 'row', flexWrap: 'wrap', gap: 14, justifyContent: 'center',
    marginHorizontal: 14, marginTop: 8, paddingVertical: 16, paddingHorizontal: 12, minHeight: 116,
    backgroundColor: '#EFE7DA', borderRadius: 14, borderWidth: 2, borderColor: '#A9885E',
    borderStyle: 'dashed',
  },
  benchEmpty: { color: '#9A8569', fontSize: 13, alignSelf: 'center', paddingVertical: 34, fontFamily: 'PKNonthaburi' },

  // ชิ้นส่วน = การ์ดของจริง (ไอคอนเด่น)
  part: { width: 96, alignItems: 'center', gap: 6 },
  partSel: { transform: [{ translateY: -4 }, { scale: 1.07 }] },
  partFace: {
    width: 84, height: 84, borderRadius: 18,
    alignItems: 'center', justifyContent: 'center',
    backgroundColor: '#F6F0E2', borderWidth: 2, borderColor: '#2C1810',
    shadowColor: '#000', shadowOpacity: 0.18, shadowRadius: 3, shadowOffset: { width: 0, height: 2 }, elevation: 3,
  },
  partFaceArt: { backgroundColor: '#F1E6CF', overflow: 'hidden' },
  partEmoji: { fontSize: 44 },
  partLabel: { color: '#4A2800', fontSize: 12, fontWeight: '700', textAlign: 'center', lineHeight: 14, fontFamily: 'PKNonthaburi' },

  // กล่องลัง — grid 2 คอลัมน์ ไม่มีกรอบ
  boxGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', paddingHorizontal: 14, marginTop: 4 },
  boxCell: { width: '48%', marginTop: 14 },
  boxLabel: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 2, paddingHorizontal: 2 },
  boxDot: { width: 10, height: 10, borderRadius: 5 },
  boxName: { color: '#4A2800', fontSize: 13, fontWeight: '800', flex: 1, fontFamily: 'PKNonthaburi' },
  boxCount: { color: '#9A8569', fontSize: 13, fontWeight: '800' },
  boxArt: { height: 128, justifyContent: 'center' },
  boxOverlay: { ...StyleSheet.absoluteFillObject, alignItems: 'center', justifyContent: 'center', paddingTop: 30 },
  boxItems: { flexDirection: 'row', flexWrap: 'wrap', gap: 2, alignItems: 'flex-end', justifyContent: 'center', paddingHorizontal: 8 },
  boxItem: { marginHorizontal: -1 },
  boxEmoji: { fontSize: 30 },
  // แผ่นรองชิ้นส่วนแบบสัญลักษณ์ (ในกล่อง) ให้ดูเป็นของจริงวางอยู่ ไม่ลอยเป็นเส้น
  chipTile: { width: 50, height: 50, borderRadius: 10, backgroundColor: '#FBF3DC', borderWidth: 1.6, borderColor: '#C9A24A', alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOpacity: 0.15, shadowRadius: 2, shadowOffset: { width: 0, height: 1 } },
  dropChip: { backgroundColor: 'rgba(44,24,16,0.6)', borderRadius: 13, paddingHorizontal: 12, paddingVertical: 5, marginTop: 4 },
  dropChipTxt: { color: '#F7F1E5', fontSize: 12, fontWeight: '700', fontFamily: 'PKNonthaburi' },

  // sequence
  // sequence — Timeline Workbench
  logBar: { marginHorizontal: 14, marginTop: 12, borderRadius: 7, borderWidth: 1.5, paddingVertical: 8, paddingHorizontal: 12 },
  logTxt: { fontSize: 12.5, fontWeight: '800', fontFamily: 'monospace', letterSpacing: 0.5 },
  logIdle: { backgroundColor: '#EFE7DA', borderColor: '#A9885E' },
  logRun: { backgroundColor: '#FBF0D2', borderColor: '#C47A2D' },
  logOk: { backgroundColor: '#E7F2DE', borderColor: '#2E7D32' },
  logErr: { backgroundColor: '#F6E3E0', borderColor: '#D94040' },
  seqHd: { color: '#6E441B', fontSize: 13, fontWeight: '900', marginHorizontal: 14, marginTop: 14, marginBottom: 7, fontFamily: 'Jersey' },
  libBox: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingHorizontal: 14, minHeight: 30 },
  libEmpty: { color: '#9A8569', fontSize: 12, fontWeight: '600', paddingVertical: 6, fontFamily: 'PKNonthaburi' },
  libCardWrap: { width: '47.5%' },
  modCard: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#EFE7DA', borderRadius: 10, borderWidth: 2, borderColor: '#2C1810', paddingVertical: 8, paddingHorizontal: 8, minHeight: 50 },
  modGood: { backgroundColor: '#E7F2DE' },
  modBad: { backgroundColor: '#F6E3E0' },
  modCharge: { backgroundColor: '#FBF0D2' },
  modQueued: { opacity: 0.5 },
  chargeRing: { position: 'absolute', left: SEQ_PADL, right: 14, top: 1, bottom: 1, borderRadius: 10, borderWidth: 2, borderColor: '#2E7D32' },
  modIcon: { width: 30, height: 30, borderRadius: 8, backgroundColor: '#F6F0E2', borderWidth: 1.5, borderColor: '#A9885E', alignItems: 'center', justifyContent: 'center' },
  modIconTxt: { fontSize: 16 },
  modLabel: { color: '#4A2800', fontSize: 12, fontWeight: '700', flex: 1, lineHeight: 15, fontFamily: 'PKNonthaburi' },
  slotRow: { flexDirection: 'row', alignItems: 'center', height: 54, marginBottom: 10, paddingLeft: SEQ_PADL, paddingRight: 14 },
  slotNum: { width: 26, height: 26, borderRadius: 13, borderWidth: 2, borderColor: '#A9885E', backgroundColor: '#F6F0E2', alignItems: 'center', justifyContent: 'center' },
  slotNumTxt: { color: '#C47A2D', fontSize: 13, fontWeight: '900' },
  slotLine: { width: 9, height: 2, backgroundColor: '#A9885E' },
  slotEmpty: { flex: 1, borderRadius: 10, borderWidth: 2, borderStyle: 'dashed', borderColor: '#B7A079', paddingVertical: 15, alignItems: 'center', backgroundColor: '#F1E8D6' },
  slotEmptyHot: { borderColor: '#C47A2D', backgroundColor: '#FBF0D2' },
  slotEmptyTxt: { color: '#9A8569', fontSize: 12, fontWeight: '700', fontFamily: 'PKNonthaburi' },
  master: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, marginHorizontal: 14, marginBottom: 20, marginTop: 10, borderRadius: 12, paddingVertical: 11, borderWidth: 2 },
  masterOff: { backgroundColor: '#E6D8BE', borderColor: '#A9885E' },
  masterOn: { backgroundColor: '#46B25E', borderColor: '#1F5E2A', shadowColor: '#2E7D32', shadowOpacity: 0.45, shadowRadius: 9, shadowOffset: { width: 0, height: 0 }, elevation: 5 },
  masterTxt: { color: '#6E441B', fontSize: 16, fontWeight: '900', letterSpacing: 0.3, fontFamily: 'PKNonthaburi' },
  swRun: { marginHorizontal: 14, marginBottom: 20, marginTop: 10, borderRadius: 12, paddingVertical: 15, alignItems: 'center', backgroundColor: '#FBF0D2', borderWidth: 2, borderColor: '#C47A2D' },
  swRunTxt: { color: '#C47A2D', fontSize: 14, fontWeight: '900', fontFamily: 'PKNonthaburi' },

  // select
  selCard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#EFE7DA', borderRadius: 12, borderWidth: 2, borderColor: '#2C1810', padding: 12 },
  selCardSel: { borderColor: '#C47A2D', backgroundColor: '#F6E8CB' },
  selCardBad: { borderColor: '#D94040', backgroundColor: '#F6E3E0' },
  selName: { color: '#4A2800', fontSize: 14, fontWeight: '800', fontFamily: 'PKNonthaburi' },
  selDesc: { color: '#6E441B', fontSize: 11.5, marginTop: 2, fontFamily: 'PKNonthaburi' },

  // diagnose
  // diagnose — จอแสดงค่า + การ์ดจุดวัด
  readout: { marginHorizontal: 14, marginTop: 12, backgroundColor: '#EBDFC6', borderRadius: 14, borderWidth: 2, borderColor: '#2C1810', paddingVertical: 14, paddingHorizontal: 16, overflow: 'hidden' },
  readoutTop: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  readoutTag: { color: '#9A6E2E', fontSize: 10.5, fontWeight: '800', letterSpacing: 1, fontFamily: 'monospace' },
  readoutPt: { color: '#6E441B', fontSize: 12.5, fontWeight: '700', flex: 1, textAlign: 'right', marginLeft: 12 },
  readoutVal: { fontSize: 32, fontWeight: '900', fontFamily: 'monospace', letterSpacing: 1 },
  scan: { position: 'absolute', top: 0, bottom: 0, width: 60, backgroundColor: '#C47A2D', opacity: 0.12 },
  // RepairBench — มัลติมิเตอร์
  dmm: { marginHorizontal: 14, marginTop: 12, backgroundColor: '#E6D8BE', borderRadius: 14, borderWidth: 2, borderColor: '#2C1810', padding: 12, gap: 10 },
  dmmScreen: { backgroundColor: '#EBDFC6', borderRadius: 9, borderWidth: 2, borderColor: '#9A7B45', paddingVertical: 8, paddingHorizontal: 14, overflow: 'hidden' },
  dmmRow: { height: 42, justifyContent: 'center' },
  dmmGhost: { position: 'absolute', left: 0, right: 0, textAlign: 'right', fontSize: 35, fontWeight: '900', fontFamily: 'monospace', letterSpacing: 3, color: '#D8C9A8' },
  dmm7: { textAlign: 'right', fontSize: 35, fontWeight: '900', fontFamily: 'monospace', letterSpacing: 3 },
  dmmTag: { color: '#9A6E2E', fontSize: 9.5, fontWeight: '700', fontFamily: 'monospace', marginTop: 3 },
  modeRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  modeLab: { color: '#6E441B', fontSize: 11, fontWeight: '800', marginRight: 2 },
  modeChip: { flex: 1, alignItems: 'center', paddingVertical: 9, borderRadius: 9, borderWidth: 2, borderColor: '#A9885E', backgroundColor: '#F6F0E2' },
  modeChipOn: { borderColor: '#C47A2D', backgroundColor: '#F6E8CB' },
  modeChipTxt: { color: '#6E441B', fontSize: 12.5, fontWeight: '800' },
  modeChipTxtOn: { color: '#A05A14' },
  coachCard: { flexDirection: 'row', gap: 10, marginHorizontal: 14, marginTop: 4, marginBottom: 2, backgroundColor: '#FBF0D2', borderRadius: 12, borderWidth: 2, borderColor: '#C47A2D', padding: 12 },
  coachAva: { fontSize: 24 },
  coachTxt: { color: '#4A2800', fontSize: 13, fontWeight: '600', lineHeight: 19, fontFamily: 'PKNonthaburi' },
  coachBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 9 },
  coachDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#D8C9A8' },
  coachDotOn: { backgroundColor: '#C47A2D', width: 16 },
  coachBtn: { backgroundColor: '#C47A2D', borderRadius: 8, paddingVertical: 7, paddingHorizontal: 16, borderWidth: 1.5, borderColor: '#2C1810' },
  coachBtnTxt: { color: '#fff', fontSize: 13, fontWeight: '800', fontFamily: 'PKNonthaburi' },
  coachSkip: { color: '#A05A14', fontSize: 11.5, fontWeight: '700' },
  // Onboarding — มาสคอตพาเล่น (dim เบา + วงเรือง + บับเบิล)
  dim: { position: 'absolute', backgroundColor: 'rgba(22,13,6,0.46)' },
  glowRing: { position: 'absolute', borderRadius: 16, borderWidth: 3, borderColor: '#FFD166', shadowColor: '#FFD166', shadowOpacity: 0.9, shadowRadius: 12, shadowOffset: { width: 0, height: 0 }, elevation: 8 },
  mascotWrap: { position: 'absolute', left: 12, right: 12, bottom: 96, flexDirection: 'row', alignItems: 'flex-end' },
  mascot: { width: 76, height: 76, alignItems: 'center', justifyContent: 'flex-end', zIndex: 2, shadowColor: '#000', shadowOpacity: 0.3, shadowRadius: 5, shadowOffset: { width: 0, height: 3 } },
  speech: { flex: 1, marginLeft: -6, marginBottom: 8, backgroundColor: '#FBF6E9', borderRadius: 16, borderWidth: 2.5, borderColor: '#C47A2D', paddingVertical: 11, paddingHorizontal: 14, shadowColor: '#000', shadowOpacity: 0.35, shadowRadius: 9, shadowOffset: { width: 0, height: 4 }, elevation: 9 },
  speechTail: { position: 'absolute', left: -9, bottom: 16, width: 0, height: 0, borderTopWidth: 8, borderBottomWidth: 8, borderRightWidth: 11, borderTopColor: 'transparent', borderBottomColor: 'transparent', borderRightColor: '#C47A2D' },
  speechTxt: { color: '#4A2800', fontSize: 14, fontWeight: '600', lineHeight: 21, fontFamily: 'PKNonthaburi' },
  speechBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 9 },
  sDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#E2D2AE' },
  sDotOn: { backgroundColor: '#C47A2D', width: 18 },
  sSkip: { color: '#A05A14', fontSize: 12, fontWeight: '800', fontFamily: 'PKNonthaburi' },
  sNext: { backgroundColor: '#C47A2D', borderRadius: 9, paddingVertical: 6, paddingHorizontal: 14, borderWidth: 1.5, borderColor: '#2C1810' },
  sNextTxt: { color: '#fff', fontSize: 12.5, fontWeight: '800', fontFamily: 'PKNonthaburi' },
  tcard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#EFE7DA', borderRadius: 12, borderWidth: 2, borderColor: '#2C1810', paddingVertical: 13, paddingHorizontal: 14 },
  tcardActive: { borderColor: '#C47A2D' },
  tcardOk: { borderColor: '#2E7D32' },
  tcardBad: { borderColor: '#C0392B' },
  // แผง PCB จุดวัด
  tpBoard: { marginHorizontal: 14, marginTop: 10, backgroundColor: '#E6D8BE', borderRadius: 14, borderWidth: 2, borderColor: '#2C1810', padding: 8, gap: 8 },
  tpItem: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#F6F0E2', borderRadius: 10, borderWidth: 2, borderColor: '#A9885E', paddingVertical: 10, paddingHorizontal: 12 },
  tpItemBusy: { borderColor: '#C47A2D', backgroundColor: '#F6E8CB' },
  tpItemOk: { borderColor: '#2E7D32' },
  tpItemBad: { borderColor: '#C0392B' },
  tpItemLabel: { color: '#4A2800', fontSize: 13.5, fontWeight: '800', flex: 1, lineHeight: 17, fontFamily: 'PKNonthaburi' },
  tpItemVal: { fontSize: 13, fontWeight: '700', fontFamily: 'monospace' },
  wireReadRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginHorizontal: 14, marginTop: 6, backgroundColor: '#10161D', borderRadius: 9, borderWidth: 1, borderColor: '#23303d', paddingVertical: 9, paddingHorizontal: 12 },
  wireReadLabel: { color: '#cdd6df', fontSize: 13, fontWeight: '700', flex: 1 },
  wireReadVal: { fontSize: 13, fontWeight: '700', fontFamily: 'monospace' },

  probeRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#EFE7DA', borderRadius: 10, borderWidth: 2, borderColor: '#2C1810', paddingVertical: 10, paddingHorizontal: 12 },
  probeLabel: { color: '#4A2800', fontSize: 12.5, fontWeight: '700', flex: 1, marginRight: 8, fontFamily: 'PKNonthaburi' },
  probeOk: { borderColor: '#2E7D32' },
  probeBad: { borderColor: '#D94040', backgroundColor: '#F6E3E0' },
  probeVal: { color: '#2E7D32', fontSize: 12, fontFamily: 'monospace' },
  diagCard: { backgroundColor: '#EFE7DA', borderRadius: 10, borderWidth: 2, borderColor: '#2C1810', paddingVertical: 11, paddingHorizontal: 12 },
  diagCardSel: { borderColor: '#C47A2D', backgroundColor: '#F6E8CB' },

  // codefill — เติมโค้ดในช่องว่าง
  codeCard: { marginHorizontal: 14, marginTop: 12, backgroundColor: '#F3ECDC', borderRadius: 10, borderWidth: 2, borderColor: '#2C1810', borderLeftWidth: 5, borderLeftColor: '#C47A2D', padding: 14 },
  codeTxt: { color: '#3B2A18', fontSize: 15, fontFamily: 'monospace', lineHeight: 24 },
  codeSlot: { color: '#A05A14', fontWeight: '900', backgroundColor: '#F6E8CB' },
  codeSlotOk: { color: '#2E7D32', backgroundColor: '#E7F2DE' },
  codeSlotBad: { color: '#B23A3A', backgroundColor: '#F6E3E0' },
  tokenRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, justifyContent: 'center', paddingHorizontal: 14, marginTop: 4 },
  token: { backgroundColor: '#EFE7DA', borderRadius: 9, borderWidth: 2, borderColor: '#C47A2D', paddingHorizontal: 18, paddingVertical: 11 },
  tokenSel: { backgroundColor: '#F6E8CB', borderColor: '#A05A14' },
  tokenTxt: { color: '#7A4A12', fontSize: 15, fontWeight: '800', fontFamily: 'monospace' },

  // polarity — ใส่ถ่านลงรางให้ถูกขั้ว
  polWrap: { paddingHorizontal: 16, paddingTop: 18, paddingBottom: 8, gap: 14, alignItems: 'center' },
  polCaption: { color: '#6E441B', fontSize: 12.5, fontWeight: '800', alignSelf: 'flex-start', marginLeft: 4, fontFamily: 'PKNonthaburi' },
  flipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, justifyContent: 'center' },
  flipBtn: { backgroundColor: '#EFE7DA', borderRadius: 11, borderWidth: 2, borderColor: '#C47A2D', paddingHorizontal: 22, paddingVertical: 11 },
  flipBtnOk: { borderColor: '#2E7D32', backgroundColor: '#E7F2DE' },
  flipTxt: { color: '#7A4A12', fontSize: 15, fontWeight: '800', fontFamily: 'PKNonthaburi' },

  // tune — เกจ + สไลเดอร์
  tuneWrap: { paddingTop: 14, paddingBottom: 10 },
  tuneVal: { color: '#C47A30', fontSize: 42, fontWeight: '900', textAlign: 'center', marginTop: 2, fontFamily: 'Jersey' },
  tuneUnit: { color: '#6E441B', fontSize: 20, fontWeight: '700' },
  tuneState: { textAlign: 'center', color: '#6E441B', fontSize: 13, fontWeight: '700', marginTop: 2, fontFamily: 'PKNonthaburi' },
  tuneSlider: { height: 46, justifyContent: 'center', marginTop: 18 },
  tuneTrack: { position: 'absolute', top: 19, height: 8, borderRadius: 4, backgroundColor: '#D7C5A2' },
  tuneTrackFill: { position: 'absolute', top: 19, height: 8, borderRadius: 4, backgroundColor: '#C47A2D' },
  tuneThumb: { position: 'absolute', top: 7, width: 34, height: 34, borderRadius: 17, backgroundColor: '#C47A2D', borderWidth: 3, borderColor: '#FBEAC6', shadowColor: '#000', shadowOpacity: 0.3, shadowRadius: 3, shadowOffset: { width: 0, height: 2 }, elevation: 4 },
  tuneHint: { color: '#6E441B', fontSize: 12.5, fontWeight: '700', textAlign: 'center', marginTop: 16, paddingHorizontal: 16, fontFamily: 'PKNonthaburi' },

  // bottom
  gbtn: { minHeight: 50, paddingHorizontal: 20, borderRadius: 12, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', borderWidth: 2, borderColor: '#2C1810' },
  gbtnTxt: { color: '#fff', fontSize: 19, fontWeight: '900', fontFamily: 'PKNonthaburi', textShadowColor: 'rgba(0,0,0,0.32)', textShadowRadius: 2, textShadowOffset: { width: 0, height: 1 } },
  runDim: { opacity: 0.45 },
  resultBox: { marginHorizontal: 14, marginBottom: 20, gap: 10, alignItems: 'center' },
  okPanel: { width: '100%', backgroundColor: '#E7F2DE', borderWidth: 2, borderColor: '#2C1810', borderRadius: 14, paddingVertical: 11, paddingHorizontal: 13 },
  okTxt: { color: '#2E5E33', fontSize: 14, fontWeight: '800', textAlign: 'center', lineHeight: 20, fontFamily: 'PKNonthaburi' },
  errPanel: { width: '100%', backgroundColor: '#F6E3E0', borderWidth: 2, borderColor: '#2C1810', borderRadius: 14, paddingVertical: 11, paddingHorizontal: 13 },
  wrongTxt: { color: '#8A2A28', fontSize: 14, fontWeight: '700', textAlign: 'left', lineHeight: 20, fontFamily: 'PKNonthaburi' },
});
